# Generated by Django 5.1.6 on 2025-03-07 18:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_jobpost_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='recruiter',
            new_name='employer',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='required_skills',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='posted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
